import type { MarqueeBrand } from "./Marquee";

export const heroPartners: MarqueeBrand[] = [
  {
    name: "Stripe",
    fontFamily: "Georgia, serif",
    fontWeight: 700,
    letterSpacing: "-0.02em",
    fontSize: "15px",
  },
  {
    name: "Coinbase",
    fontFamily: "Arial, sans-serif",
    fontWeight: 900,
    letterSpacing: "0.08em",
    fontSize: "13px",
    extraClasses: "uppercase",
  },
  {
    name: "Uniswap",
    fontFamily: '"Trebuchet MS", sans-serif',
    fontWeight: 600,
    letterSpacing: "0.01em",
    fontSize: "15px",
    extraClasses: "italic",
  },
  {
    name: "Aave",
    fontFamily: '"Courier New", monospace',
    fontWeight: 700,
    letterSpacing: "0.12em",
    fontSize: "13px",
    extraClasses: "uppercase",
  },
  {
    name: "Compound",
    fontFamily: 'Palatino, "Book Antiqua", serif',
    fontWeight: 400,
    letterSpacing: "-0.01em",
    fontSize: "16px",
  },
  {
    name: "MakerDAO",
    fontFamily: 'Impact, "Arial Narrow", sans-serif',
    fontWeight: 400,
    letterSpacing: "0.04em",
    fontSize: "14px",
  },
  {
    name: "Chainlink",
    fontFamily: "Verdana, sans-serif",
    fontWeight: 700,
    letterSpacing: "-0.03em",
    fontSize: "13px",
  },
];

export const backerPartners: MarqueeBrand[] = [
  {
    name: "Fundamental Labs",
    fontFamily: '"Times New Roman", serif',
    fontWeight: 400,
    letterSpacing: "0.02em",
    fontSize: "14px",
  },
  {
    name: "KUCOIN",
    fontFamily: '"Arial Black", sans-serif',
    fontWeight: 900,
    letterSpacing: "0.08em",
    fontSize: "16px",
  },
  {
    name: "NGC",
    fontFamily: "Impact, sans-serif",
    fontWeight: 700,
    letterSpacing: "0.05em",
    fontSize: "18px",
  },
  {
    name: "NxGen",
    fontFamily: "Georgia, serif",
    fontWeight: 600,
    letterSpacing: "-0.02em",
    fontSize: "17px",
  },
  {
    name: "Matter Labs",
    fontFamily: "Helvetica, sans-serif",
    fontWeight: 700,
    letterSpacing: "-0.01em",
    fontSize: "15px",
  },
  {
    name: "DEXTools",
    fontFamily: "Verdana, sans-serif",
    fontWeight: 700,
    letterSpacing: "0.06em",
    fontSize: "14px",
    extraClasses: "uppercase",
  },
  {
    name: "NGRAVE",
    fontFamily: '"Courier New", monospace',
    fontWeight: 700,
    letterSpacing: "0.18em",
    fontSize: "14px",
  },
  {
    name: "Polychain",
    fontFamily: "Palatino, serif",
    fontWeight: 500,
    letterSpacing: "0.03em",
    fontSize: "15px",
  },
];
